
name: Build dotnet application

on:
  workflow_call:
    inputs:
      runs-on:
        description: Platform to execute on
        type: string
        default: ubuntu-latest
        
      dotnet-version:
        description: Version of dotnet to use
        type: string
        default: 5.0.x
      
      project-folder:
        description: The folder containing the project to build
        type: string
        default: .
        
      run-tests:
        description: Run tests
        type: boolean
        default: true
      
      publish-configuration:
        description: Configuration to publish
        type: string
        default: Release
        
      artifact-name:
        description: Name of the artifact to upload
        type: string
        default: drop
        
      release-branches:
        description: Name of the artifact to upload
        type: string
        required: true
    
jobs:
  build:
    name: Build dotnet app
    
    runs-on: ${{ inputs.runs-on }}
    defaults:
      run:
        working-directory: ${{ inputs.project-folder }}
    
    steps:
      - uses: actions/checkout@v2
      - name: get branch name
        id: release-gates
        run: |
         echo ${{ github.ref_name }}
         branch=$(echo ${{ inputs.release-branches }} |tr -d ' '|tr ',' '\n'|grep -x ${{ github.ref_name }}) || true
       
         if [ $branch == ${{ github.ref_name }} ]; then
            echo '::set-output name=apply::true'
         else
            echo '::set-output name=apply::false'
         fi
      - name: check release gates
        if: ${{  steps.release-gates.outputs.apply }}
        run: |
           echo ${{ steps.release-gates.outputs.apply }}
         
         
